// File generated by FlutterFire CLI.
// This file provides platform-specific Firebase configuration constants.
// To regenerate: `flutterfire configure`
// Generated by: Roomix Project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// Example usage in main.dart:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'roomix-28de2.firebaseapp.com'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'roomix-28de2'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'roomix-28de2.appspot.com'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '123456789012'),
    appId: String.fromEnvironment('FIREBASE_APP_ID', defaultValue: '1:123456789012:web:abcdef1234567890abcdef'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'roomix-28de2',
    storageBucket: 'roomix-28de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'roomix-28de2',
    storageBucket: 'roomix-28de2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:macos:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'roomix-28de2',
    storageBucket: 'roomix-28de2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:windows:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'roomix-28de2',
    storageBucket: 'roomix-28de2.appspot.com',
  );
}
